### ISSUE TITLE
Update collider verticies

### ISSUE THREAD

**Issue by Shatur** [Jondolf/bevy_xpbd#102]
I have a wall creation system and my game and I need to update colliders when player change walls.
Currently I just create new collider trimesh every update. But it would be better if I could replace the old trimesh with a new one to avoid reallocation (from slice, for example).

**Comment by Jondolf** [comment]
I'm not super familiar with Parry's internals, but I'm not sure if it's currently possible to modify the trimesh shape without creating a new trimesh instance, as I'm not seeing any methods for doing that in [`SharedShape`](https://docs.rs/parry2d/latest/parry2d/shape/struct.SharedShape.html) or [`TriMesh`](https://docs.rs/parry2d/latest/parry2d/shape/type.TriMesh.html). As far as I know, the shape has to be replaced with a new one if you want to change the geometry.

**Comment by Shatur** [comment]
Got it, should be reported to Parry then.

**Comment by Jondolf** [comment]
To clarify, I think you can get a mutable reference to a trimesh collider's internal shape like this:

```
let shape = collider.get_shape_mut().as_trimesh_mut().unwrap();
```

It returns a [`GenericTriMesh`](https://github.com/dimforge/parry/blob/3ac8e405e26041db57acb6b2218c31066ee7cb6b/src/shape/trimesh.rs#L350C18-L350C18), but `vertices` is private and I'm not seeing a way to get a mutable reference unless I'm missing something.
