### ISSUE TITLE
Center of mass behaves incorrectly for off-center colliders

### ISSUE THREAD

**Issue by jpetkau** [Jondolf/bevy_xpbd#108]
If I make a rigid body with a single capsule collider with an off-center origin, e.g.:

    // 1m tall character with origin at (0,0); using Z-up so gravity is (0, 0, -9.8)
    SharedShape::capsule(point3(0.0, 0.0, 0.25), point3(0.0, 0.0, 0.75), 0.25),

If I inspect the inferred CenterOfMass component, it correctly shows as `CenterOfMass(Vec3(0.0, 0.0, 0.5))`. However the object behaves as if the center of mass was at `(0, 0, -0.5)`, so the capsule wobbles upright on one end instead of falling over.

The same thing happens if I make a centered capsule and use a compound collider to offset it:

```
    let cap = SharedShape::capsule_z(0.25, 0.25);
    let xf = Isometry3::translation(0.0, 0.0, 0.5);
    let c = SharedShape::compound(vec![(xf, cap)]);
```

[Actually the same thing happens in 2.0. In the latest it fails on a `todo` in `as_support_map` for `compound`.]

Colliders seem to work fine if their center of mass is (0,0,0).

(I haven't made a small repro for this yet but I can.)

**Comment by Jondolf** [comment]
I can repro weird behaviour with off-center center of mass. Here I'm just moving a slightly off-center capsule back and forth, and it rocks from side to side weirdly, and when it flips on the other side, it jumps up:

https://github.com/Jondolf/bevy_xpbd/assets/57632562/d281bc4d-6884-4753-89ab-20b4733d33cd

Thanks for reporting the issue, I'll look into it more in depth soon
