### ISSUE TITLE
Change RigidBody in system

### ISSUE THREAD

**Issue by volodalexey** [Jondolf/bevy_xpbd#132]
If it possible to change `RigidBody` ?
I want to change from `RigidBody::Kinematic => RigidBody::Dynamic` in some system.
I can not find any example how to do this.

**Comment by Jondolf** [comment]
You should be able to just query for the component and set the enum variant:
(haven't tested)
```rust
fn my_system(mut query: Query<&mut RigidBody>) {
    for mut rb in &mut query {
        *rb = RigidBody::Dynamic;
    }
}
```

**Comment by volodalexey** [comment]
Ohh. Thanks! I missed this. It ried `Query<RigidBody>` and got error and I forgot to add `&`.
