### ISSUE TITLE
Make `PhysicsLoop::accumulator` public?

### ISSUE THREAD

**Issue by RubenAngelov** [Jondolf/bevy_xpbd#147]
I'm writing some interpolation code that keeps track of Transforms from the previous physics tick and interpolates between that and the current Transform every regular update, storing it in a separate entity for rendering. Problem is I need access to `PhysicsLoop::accumulator`, which currently is private (because of `pub(crate)`). Could this be changed?

 Also noticed that the `PhysicsLoop` can't be found in the docs.

**Comment by Jondolf** [comment]
`accumulator` (and `queued_steps`) are now public on main. `PhysicsLoop` is technically in the docs ([here](https://docs.rs/bevy_xpbd_3d/latest/bevy_xpbd_3d/plugins/setup/index.html)) but it's very obscure, so I'll add proper docs for it and some other scheduling things at some point.
