### ISSUE TITLE
The trait bound `bevy_xpbd_3d::components::Position: bevy::prelude::Component` is not satisfied

### ISSUE THREAD

**Issue by floppyhammer** [Jondolf/bevy_xpbd#157]
When using xpbd and bevy as crates, if I use a local bevy repository (by using path = "../bevy" in Cargo.toml), the compiler complains about

```
the trait `bevy::prelude::Component` is not implemented for `bevy_xpbd_3d::components::Position`
```

Any advice?

**Comment by Jondolf** [comment]
Yeah this is most likely just a version mismatch issue that can be fixed via patches and/or forks. Further discussion probably makes more sense here: https://github.com/bevyengine/bevy/discussions/9869
