### ISSUE TITLE
`trimesh_shapes_3d` example broken: shapes jumping around randomly [Mac M1 Sonoma]

### ISSUE THREAD

**Issue by vidhanio** [Jondolf/bevy_xpbd#158]
https://github.com/Jondolf/bevy_xpbd/assets/41439633/c6bd4dc9-985c-46e5-bd51-9ab0c0e31e5e

**Comment by Jondolf** [comment]
Yep, this is an issue that should get fixed by #156.

**Comment by vidhanio** [comment]
seems to work as expected now! :)
