### ISSUE TITLE
Remove `Pos` and `Rot` in favor of bevy's `Transform`

### ISSUE THREAD

**Issue by Jondolf** [Jondolf/bevy_xpbd#16]
Currently, `bevy_xpbd` uses the components `Pos` and `Rot` for describing the position and orientation of bodies. At the end of each iteration of the main physics loop, these are synchronized with bevy's `Transform`s.

I'd like to discuss if we should remove the separate components and move to just using bevy's own `Transform`s.

## Advantages

- More familiar and convenient for bevy users
- More complete APIs
- Reduces code and maintenance overhead (for example, no custom `Rot` implementations for 2D and 3D, all rotations use `Quat`s)
- Less components and nicer queries (`Transform` and `PrevTransform` instead of `Pos`, `PrevPos`, `Rot`, and `PrevRot`)
- No need for synchronization step
- If/when bevy gets an editor eventually, it would make more sense to manipulate `Transform`s directly
- It's what most physics engines seem to do (like `bevy_rapier`)

## Disadvantages

- `Transform` hierarchies, scaling and shearing can cause serious problems (see comments below)
- Parallellism might be harder, since two systems can't access the same `Transform` at once. Separate systems with `Pos` and `Rot` can run simultaneously.
- No `f64` version of `Transform` unless we make a custom one (adding `f64` as a crate feature: #7)
- In 2D, `Pos` uses `Vec2` and `Rot` uses a scalar value. `Transform`s just have a `Vec3` and a `Quat`, which can be considered less ergonomic for 2D. However, bevy users are used to working with them, and they might provide more freedom, so this may not be an issue.
- Migration pain (not a problem for us now, but could be in the future if this crate becomes more popular)
- Something else?

## Conclusion

Personally, at least from an API standpoint, I think it makes sense to move to using just `Transform`s, as it would generally be much more convenient and familiar for bevy users, and it would also probably reduce the engine's code and complexity. Using `Transform`s for physics can cause many problems as well though, which is why I'd like to hear what others think.

**Comment by Aceeri** [comment]
https://github.com/dimforge/bevy_rapier/pull/219#issuecomment-1194383319
Some discussion on this from @HackerFoo

**Comment by HackerFoo** [comment]
Physics uses isometries (no scale or shear), and these must be global (from the physics engine's point of view), so it's not a good match for `Transform`. Implementing `From` / `Into` makes it easy to convert between transform types.

**Comment by HackerFoo** [comment]
Putting the rotation and translation together in a struct can make the math a lot cleaner, though. I use two types of isometries: one with a `Quat` rotation for positions and one with a `Vec3` torque (cross product) for forces, which accumulate properly.

**Comment by johanhelsing** [comment]
> No f64 version of Transform unless we make a custom one

in my opinion, this alone is reason enough not to use `Transforms`.

From my previous attempts with `Transform`s my original bevy_xpbd and 2D, it was pretty painful / non-ergonomic to use from the outside as well.

> I think something that might make sense is to have the Pos/Rot take the Transform when it is initially created, which would give us the benefits of being able to set Transforms for initialization.

> Implementing From / Into makes it easy to convert between transform types.

Yeah, I think this could work quite nicely with the builder methods on `RigidBodyBundle`:

I also think it's nice to be able to run a simulation that *doesn't* sync back to the bevy transforms. Could easily integrate with crates like [seldom_pixel](https://github.com/Seldom-SE/seldom_pixel/) for instance, or physics simulations that don't really need to render every frame (or at all)

On the topic of granularity of components: In the version of bevy_xpbd I use in cargo space (derived from the same source as this repo), I use the presence of components to communicate what a physics entity can and cannot do. e.g.:

- if it doesn't have mass or any kind of velocity (angular or linear), it's a static
- if it doesn't have angular velocity, its rotation is locked (ideal for particles)
- if it doesn't have a collider, it won't be included in the penetration constraints
- means a lot of queries don't have overlap, so more systems can run in parallel
- and easy to iterate over dynamics vs statics based on query filters

**Comment by Jondolf** [comment]
I agree with everyone's points here, I think we should stick with `Pos` and `Rot` as separate components. This is more explicit and provides flexible and non-overlapping queries, while avoiding the `Transform` problems related to hierarchy, shear, scale, `f64` etc. The primary gains of moving to `Transform` would probably just be familiarity and ergonomics, and even that's debatable.

I think this was still a worthwile discussion to have, at least for future reference. I'll close this now :)
