### ISSUE TITLE
Sometimes CollidingEntities will accumulate all the collided entities, sometimes not

### ISSUE THREAD

**Issue by rewin123** [Jondolf/bevy_xpbd#161]
![image](https://github.com/Jondolf/bevy_xpbd/assets/10954133/76ef2f13-d2c1-4965-9812-0adbbf68936a)

Sometimes CollidingEntities starts behaving incorrectly. Sometimes after the end of a collision with an object, its entity is not removed from the list, resulting in a hang in the air for the player's dynamic controller, as shown below. In case the incorrect behavior of the component has started, it starts accumulating in CollidingEntities all entities it has encountered. Sometimes incorrect behavior is not observed.

Cube controller code:

```rust

app.add_systems(PhysicsSchedule, move_player.run_if(in_state(EditorState::Game)).before(PhysicsStepSet::BroadPhase))

...

fn move_player(
    keyboard_input: Res<Input<KeyCode>>,
    mut query: Query<(Entity, &mut LinearVelocity, &mut AngularVelocity, &PlayerController, &CollidingEntities, &mut Transform)>,
    time : Res<Time>
) {
    for (e, mut vel, mut rot, controller, colliding, tranform) in query.iter_mut() {
        if colliding.len() > 0 {
            info!("colliding: {:?}", colliding);
            
            let frw = tranform.forward();
            let up = tranform.up();

            let mut target_vel = Vector::new(0.0, 0.0, 0.0);
            if keyboard_input.pressed(KeyCode::W) {
                target_vel += frw;
            }
            if keyboard_input.pressed(KeyCode::S) {
                target_vel -= frw;
            }
            //rotate
            if keyboard_input.pressed(KeyCode::A) {
                rot.y = 2.0;
            } 
            if keyboard_input.pressed(KeyCode::D) {
                rot.y = -2.0;
            }
            if !keyboard_input.pressed(KeyCode::A) && !keyboard_input.pressed(KeyCode::D) {
                rot.y -= 10.0 * rot.y * time.delta_seconds();
            }
            
            target_vel *= controller.speed;

            if keyboard_input.pressed(KeyCode::Space) {
                target_vel += up * controller.jump_speed;
            }

            //smooth change vel
            let cur_vel = vel.0.clone();
            let cur_vel = vel.0 + (target_vel - cur_vel) * 10.0 * time.delta_seconds();
            vel.0 = cur_vel;

        } else {

        }
    }    
}
```

Full code can be founded at https://github.com/rewin123/space_editor/blob/v0.1/examples/platformer.rs

Tested on [8b2ea8f](https://github.com/Jondolf/bevy_xpbd/commit/8b2ea8fd4754fb3ecd51f79fad282d22631d2c7f) in main branch

**Comment by Jondolf** [comment]
Hi, I finally finished up the work for #112. I tested your example and it now seems to be updating `CollidingEntities` correctly.

Cool project btw! Looks very useful :)

**Comment by rewin123** [comment]
Thanks for the fix. xpbd project is also very useful, could be said a small revolution for bevy:)
