### ISSUE TITLE
An example for `ExternalForce`.

### ISSUE THREAD

**Issue by musjj** [Jondolf/bevy_xpbd#162]
I'm trying to figure out how to apply a force to the player, but I can't figure out how.

I have roughly something like this:

```rust
commands.spawn((
    ...
    RigidBody::Dynamic,
    ExternalForce::default(),
    Player,
));

fn system(mut force_query: Query<&mut ExternalForce, With<Player>>) {
    for mut force in &mut force_query {
        force.apply_force(Vec2::Y * 10.);
    }
}
```

But doing so have no effect on the player. I can query and mutate the velocity instead and it will work, so I know that my code is not completely broken at least.

**Comment by Jondolf** [comment]
It looks like your example is in 2D, so it's likely that your player's size is around 100px or so. Applying 10 Newtons of force won't have almost any impact on a body that is so large in physics units. My guess is that you should apply 10 or a 100 times more force to see the effect. Let me know if it works :)

This would probably be easier if we had something like Rapier's `pixels_per_meter` physics scale, which would allow you to specify 100px = 1 meter so you could use smaller forces. I have plans to add this at some point

**Comment by musjj** [comment]
You're right, you need huge numbers for it to take effect: `force.apply_force(Vec2::Y * 100000.)` (also the force component is added automatically apparently). A physics scale would definitely be useful, looking forward to that!
