### ISSUE TITLE
`keyboard_input.just_pressed` in `basic_dynamic_character` example works only sometimes

### ISSUE THREAD

**Issue by silentbat** [Jondolf/bevy_xpbd#170]
Very new to bevy_xpbd, I hope this is not a silly question..

**What I did:**
run the "basic_dynamic_character" example in release mode

`cargo run --example basic_dynamic_character --release`

and then press space/jump multiple times.

**What I expected to happen:**
the capsule/character should jump every time I press space, as long as it touches the ground when pressing.

**What happened:**
the jump happens only sometimes, seems random at first.

I think the problem is that the system responsible for keyboard input handling is _running on the physics schedule_ and therefore `.just_pressed()` is not working as expected (keys are not _just_ pressed anymore in most cases but only _pressed_).

All other buttons are working fine, as well as the grounded condition. Also: when changing the [line](https://github.com/Jondolf/bevy_xpbd/blob/884a233fc698ca52652061c344341e2d595caa92/crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs#L107) to
    `if keyboard_input.pressed(KeyCode::Space) && !ground_hits.is_empty() {`
the jumping works as intended.

Is it just me that I am not familiar enough with bevy_xpbd to know what I should do in such cases or should the example be "fixed"?

**Comment by stargazing-dino** [comment]
Yeah, I noticed the same behavior in my own game which I resolved by placing my jump code in an `Update` schedule. I think this is a bevy issue though and not a xpbd issue: https://github.com/bevyengine/bevy/issues/6183

I think one workaround could be to separate out the input handling logic into an update schedule and have that just send events. You could then consume those events in the actual movement code [similar to here](https://bevy-cheatbook.github.io/patterns/manual-event-clear.html)
