### ISSUE TITLE
Enhancement: add Dominance groups like Rapier?

### ISSUE THREAD

**Issue by mattdm** [Jondolf/bevy_xpbd#177]
I'm having some frustrations with Rapier for Bevy, and thought I'd give this a try. However, one thing I'm pleased with in my current setup is: attaching a rigid body and collider to a camera, and moving that with external forces. I get nice, smooth motion and the camera doesn't go through things. But, I also don't want the camera to _push_ stuff in the world. Rapier has "dominance groups" which can be used for this -- anything with a lower value is affected by but does not affect anything else. (This is separate from collision groups / collision layers, since it's asymmetrical.) 

https://rapier.rs/docs/user_guides/bevy_plugin/rigid_bodies#dominance

Unless I am missing it, there is currently no equivalent in xpbd. It would be nice to have, for my use case at least, and probably others!

**Comment by Jondolf** [comment]
Thanks, I'll add this to my todo list. Should be pretty straightforward to add, so I might be able to get it into 0.3 (will be released in roughly a week).

**Comment by Jondolf** [comment]
This was so straightforward that I actually went ahead and just implemented it already in #178. I'll test the PR more tomorrow to make sure everything works as expected, but I'll get it merged during the next couple of days.
