### ISSUE TITLE
Partial sensor entities 

### ISSUE THREAD

**Issue by umut-sahin** [Jondolf/bevy_xpbd#193]
Hi, thanks for the amazing library!

Here is my use case:
- I want the player to trigger collision response against walls.
- I **don't** want the player to trigger collision response against enemies.
- I want the player to trigger collision events with enemies.

Which means the player needs to be a regular physics object against walls, but sensor against enemies.

Right now, I'm spawning two entities for the player, one for physical collisions and one for sensor collisions, but these need to be synced with each other at some point. I'm doing that in the update. I'm sure this will cause problems as they might get out of sync within the physics world.

Is there a better way to achieve this?

**Comment by Jondolf** [comment]
On the main branch (and soon 0.3), one approach would be to use child colliders (#154) which were just merged.

You could give the player a normal collider with collision layers to avoid collision response against enemies, and add a child collider as a sensor that can trigger collision events for all layers. Roughly like this:

```rust
commands.spawn((
    RigidBody::Dynamic,
    Collider::capsule(1.0, 0.4),
    CollisionLayers::new([Layer::Player], [Layer::Environment]),
))
.with_children(|child_builder| {
    child_builder.spawn((
        Collider::capsule(1.0, 0.4), // or whatever shape you want
        Sensor,
    ));
});
```

Child colliders should be automatically synced properly.

**Comment by umut-sahin** [comment]
That's exactly what I was looking for! Thanks.
