### ISSUE TITLE
Involuntary rotation of character

### ISSUE THREAD

**Issue by yogo1212** [Jondolf/bevy_xpbd#213]
Hi :-)

My blob character from the 'basic dynamic character' example is experiencing rotational forces when moving sideways.
I've added a camera that stays behind the character and looks in front of it.
The example code only allows applying forces in the X and Z direction, yet the camera turns after while of fumbling around:

![2023-10-30T09:17:39,751321750+01:00](https://github.com/Jondolf/bevy_xpbd/assets/5165324/8dc2d157-59ca-49f6-a76b-eb569e36933d)

```
    if ground_hits.is_empty() {
      continue;
    }

    // Directional movement
    if keyboard_input.pressed(KeyCode::W) || keyboard_input.pressed(KeyCode::Up) {
      linear_velocity.z -= 1.2;
    }
    if keyboard_input.pressed(KeyCode::S) || keyboard_input.pressed(KeyCode::Down) {
      linear_velocity.z += 1.2;
    }
    if keyboard_input.pressed(KeyCode::A) || keyboard_input.pressed(KeyCode::Left) {
      linear_velocity.x -= 1.2;
    }
    if keyboard_input.pressed(KeyCode::D) || keyboard_input.pressed(KeyCode::Right) {
      linear_velocity.x += 1.2;
    }

    // Jump if space pressed and the player is close enough to the ground
    if keyboard_input.just_pressed(KeyCode::Space) {
      linear_velocity.y += 8.0;
    }

    // Slow player down on the x and y axes
    linear_velocity.x *= 0.8;
    linear_velocity.z *= 0.8;
```

Is that to be expected? How could I correct for it?

**Comment by yogo1212** [comment]
Ooops!

There's been an update by @Jondolf - looks promising.
I'll try that and close this issue if it works with the change.

**Comment by Jondolf** [comment]
Yep, that update should fix this. I forgot to lock rotation around the Y axis so friction causes rotation.

**Comment by Jondolf** [comment]
I'm also further updating the character controller examples in #212 to be more complete and support both keyboard and gamepad input.

**Comment by yogo1212** [comment]
@Jondolf That's suuuuuper cool!

Thank you very much, stranger from the land of myths and metal :wink:

**Comment by Jondolf** [comment]
The updates are now merged so I'll close this
