### ISSUE TITLE
Running at a fixed timestep is broken in 0.3.0

### ISSUE THREAD

**Issue by rubengrim** [Jondolf/bevy_xpbd#223]
In 0.3.0, changing the timestep seems to have no effect on how often `PhysicsSchedule` is run, although velocities are scaled as they should. This means that movement is completely timestep-dependant.

In 0.2.0, running
```rust
use bevy::prelude::*;
use bevy_xpbd_3d::{prelude::*, PhysicsSchedule, PhysicsStepSet};

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, PhysicsPlugins::default()))
        .insert_resource(PhysicsTimestep::Fixed(1.0 / 10.0))
        .add_systems(
            PhysicsSchedule,
            from_physics.in_set(PhysicsStepSet::BroadPhase),
        )
        .add_systems(Update, from_main)
        .run();
}

fn from_main() {
    println!("from main");
}

fn from_physics() {
    println!("from physics");
}
```
prints "from main" every frame and "from physics" every ~8 frames, which is expected given a framerate of ~80 and a physics timestep of 0.1.

The equivalent code in 0.3.0 below runs both systems every frame.
```rust
use bevy::prelude::*;
use bevy_xpbd_3d::{prelude::*, PhysicsSchedule, PhysicsStepSet};

fn main() {
    App::new()
        .add_plugins((DefaultPlugins, PhysicsPlugins::default()))
        .insert_resource(Time::new_with(Physics::fixed_hz(1.0 / 10.0)))
        .add_systems(
            PhysicsSchedule,
            from_physics.in_set(PhysicsStepSet::BroadPhase),
        )
        .add_systems(Update, from_main)
        .run();
}

fn from_main() {
    println!("from main");
}

fn from_physics() {
    println!("from physics");
}
```

If a kinematic rigidbody is spawned with a constant linear velocity, it speeds up as the timestep is increased. I'm assuming the issue is that physics updates are scaled as if they're done less frequently, but are actually done every frame.

**Comment by Jondolf** [comment]
Yep, the fixed timestep is currently broken and frame rate dependent. I somehow didn't notice this in the examples since a lot of them multiplied by delta time and I had VSync on so it was locked to 60 FPS. I'll release a 0.3.1 patch soon
