### ISSUE TITLE
Debug render hides the entire rendering

### ISSUE THREAD

**Issue by rewin123** [Jondolf/bevy_xpbd#240]
### Version
0.3

### What's going wrong

Debug render hides the entire rendering (both normal meshes and debug meshes), with a certain sequence of render flags changing. 

If you change PhysicsDebugConfig parameters in the following order:

1. enabled = true
2. hide_meshes = true
3. enabled = false

then all meshes that have colliders are hidden and the debug renderer is not displayed. Example on the gif

![ezgif-5-3e954ccb70](https://github.com/Jondolf/bevy_xpbd/assets/10954133/7bdb4012-9623-4b69-b77a-ed3f1fb40174)

egui code from gif
```rust
ui.heading("Bevy XPBD 3D");
ui.checkbox(
    &mut world
        .resource_mut::<bevy_xpbd_3d::prelude::PhysicsDebugConfig>()
        .enabled,
    "Show bevy xpbd debug render",
);
ui.checkbox(
    &mut world
        .resource_mut::<bevy_xpbd_3d::prelude::PhysicsDebugConfig>()
        .hide_meshes,
    "Hide debug meshes",
);
```

**Comment by Jondolf** [comment]
Should be fixed by #242 so that mesh visibility for bodies and colliders is enabled again when `enabled` is `false`.
