### ISSUE TITLE
Serde Serialization

### ISSUE THREAD

**Issue by ImVexed** [Jondolf/bevy_xpbd#243]
Hello! I was wondering what to do about serializing components like `LinearVelocity`. It seems they don't support serialization, and there's no flag I can add to enable it.

**Comment by Jondolf** [comment]
Hi! I can try to add a feature flag for serde serialization today or tomorrow.

**Comment by ActuallyHappening** [comment]
Yes this is a much wanted addition please!
How can this library not support serde? I feel like serde should have snuck in somewhere by now
