### ISSUE TITLE
Collider example from documentation not working as expected

### ISSUE THREAD

**Issue by dafteran4** [Jondolf/bevy_xpbd#245]
This is from Collider docs. But the 'Transform' component has no effect, the ball is not spawned at desired height. If replaced with 'Position' component, it works as expected. 

```
// Spawn a dynamic body that falls onto a static platform
fn setup(mut commands: Commands) {
    commands.spawn((
        RigidBody::Dynamic,
        Collider::ball(0.5),
        Transform::from_xyz(0.0, 2.0, 0.0),
    ));
    commands.spawn((RigidBody::Static, Collider::cuboid(5.0, 0.5, 5.0)));
}
```

**Comment by Jondolf** [comment]
Ah, yeah you need `GlobalTransform` for it to be positioned correctly. The docs should be updated to fix that example though
