### ISSUE TITLE
Rotational motion ignores center of mass

### ISSUE THREAD

**Issue by mbrea-c** [Jondolf/bevy_xpbd#246]
### Problem
When given an angular velocity, rigidbodies that have a non-zero local center of mass seem to rotate around their `Position`, ignoring `CenterOfMass`:

https://github.com/Jondolf/bevy_xpbd/assets/31567043/9050e518-7ff3-4e2f-b50f-a9fd3d96d7dc

Code for reproducing:
```rust
    // floor
    commands
        .spawn(PbrBundle {
            mesh: meshes.add(shape::Box::new(40., 0.3, 40.).into()),
            material: materials.add(Color::WHITE.into()),
            ..default()
        })
        .insert(RigidBody::Static)
        .insert(Collider::cuboid(40., 0.3, 40.));

    // cube
    commands
        .spawn(SpatialBundle {
            transform: Transform {
                translation: Vec3::new(0.0, 2.0, 0.0),
                ..default()
            },
            ..default()
        })
        .insert(RigidBody::Dynamic)
        .insert(AngularVelocity(Vec3::new(0., 7., 0.)))
        .insert(LinearVelocity(Vec3::new(0., 7., 0.)))
        .with_children(|b| {
            b.spawn(SpatialBundle {
                transform: Transform {
                    translation: Vec3::new(1.5, 0., 0.),
                    ..default()
                },
                ..default()
            })
            .insert(Collider::cuboid(1., 1., 1.));
        });
```

### Possible solution

First, is this unintended or am I missing something? If it's unintended, we might want to account for the center of mass during integration. For reference, this is what rapier does: [link](https://github.com/dimforge/rapier/blob/master/src/dynamics/rigid_body_components.rs#L566)

Updating `integrate_rot` in `integration.rs` and `update_lin_vel` in `solver.rs` to account for offset centers of mass makes the rotation work as expected, but seems to introduce a number of other issues (exploding velocity on contact, object suddenly speeding up when adjusting timescale). Any suggestions on how best to fix this?

thanks :)

**Comment by dafteran4** [comment]
Are there any good reasons to not have rigid body position by definition equal to its center of mass? It seems it would simplify things considerably and make everything easier to reason about. From physical perspective there is no position to rigid body but its center of mass. It's just an inconvenient additional transform without any physical properties. I may be missing some practical application though. :)

**Comment by dafteran4** [comment]
You're right, this seems to be the convention, and changing the colliders would cause 'jump' in com/position.  

I was thinking from API perspective, if you add a rigid body with many colliders (children), you can't really say in advance what the 'position' of this body actually is, you only care about the colliders and the inertial properties they produce (center of mass). It all works well, but you end up with a rigid body with some meaningless 'position', initially 0,0,0, if no transform is set on the rigid body.
