### ISSUE TITLE
Wrong generalized inverse masses in solve_vel

### ISSUE THREAD

**Issue by felixbjorkeson** [Jondolf/bevy_xpbd#29]
I am pretty sure that the generalized inverse masses calculated in solve_vel should be based on the delta_v direction not the collision normal?

**Comment by Jondolf** [comment]
Thanks, I believe you're right. I probably just used the normal when I implemented restitution and forgot to change it to the delta_vel direction when I added dynamic friction.

I'll fix this soon, probably as a part of fixing #2 if it ends up being related in any way.

**Comment by Jondolf** [comment]
You were right, it's supposed to use the normalized `delta_v`. Just using `normal` causes explosive friction in many cases, as can be seen in #47. Thanks for spotting the issue and sorry for fixing it so late 😅
