### ISSUE TITLE
kenimatic_character_3d example

### ISSUE THREAD

**Issue by Nacir1i** [Jondolf/bevy_xpbd#299]
The kenimatic_character_3d example is missing plane ground. it a very simple fix i can make a PR if you would like

**Comment by Jondolf** [comment]
I'm not quite sure what you mean, it does have the ground for me?

![kuva](https://github.com/Jondolf/bevy_xpbd/assets/57632562/9c251d7e-69ee-4105-8dbd-8596a0678bd2)

**Comment by Nacir1i** [comment]
my mistake. I missed that part 😅😅. I'll close this issue
