### ISSUE TITLE
`Collider::set_shape` won't work if scale is not changed

### ISSUE THREAD

**Issue by hxYuki** [Jondolf/bevy_xpbd#301]
![image](https://github.com/Jondolf/bevy_xpbd/assets/15306248/a3cda0f1-ee87-423b-b9e3-7687f770c7ce)

`set_shape` will be ignored if not setting scale.

**Comment by Jondolf** [comment]
Is this on the main branch or in 0.3? I believe this should've been fixed by #278.

**Comment by hxYuki** [comment]
It seems that the fix is not applied on the crate version.
![image](https://github.com/Jondolf/bevy_xpbd/assets/15306248/38dcd9e8-8bf7-4454-86c7-d67cced2f938)

**Comment by Jondolf** [comment]
Yeah, the fix isn't in 0.3 yet, but it is on the main branch and will be in 0.4
