### ISSUE TITLE
Feature Request: Add ellipse collider.

### ISSUE THREAD

**Issue by 443eb9** [Jondolf/bevy_xpbd#317]
Ellipse is also a common shape.

**Comment by Jondolf** [comment]
Ellipses aren't supported as a built-in shape in the Parry collision detection library, but it should support custom colliders, so I'll try to implement it for next release. Bevy is getting geometric primitives for 0.13, which includes ellipses and more exotic shapes like conical frusta, and I'm trying to add support for all of these shapes (and also regular polygon colliders which are currently missing).
