### ISSUE TITLE
[0.4.1] Colliders are initialized with wrong transform

### ISSUE THREAD

**Issue by hxYuki** [Jondolf/bevy_xpbd#334]
![image](https://github.com/Jondolf/bevy_xpbd/assets/15306248/bedbdcb9-1a44-48c0-910b-3dc5e366c4b1)

Colliders are created ignoring the entity transform from sprite bundle.

**Comment by Jondolf** [comment]
This was also reported on Discord, and seems to only affect colliders that don't have a `RigidBody` component. This was caused by a scheduling issue. I released a 0.4.2 patch that should fix this; if not, feel free to reopen
