### ISSUE TITLE
issues with 2D heightfield collider 

### ISSUE THREAD

**Issue by shnewto** [Jondolf/bevy_xpbd#342]
hello! 

I've been trying to get the 2D heightfield collider to work for me and can't seem to 🙃  I can use the parry `SharedShape`and `Collider::from` however and it made me curious to look at the implementation here in xpbd.

Here's the code that works for me using `SharedShape`and `Collider::from`

```
    let x_scale = heights.len() as f32 - 1.0; // this is 511.0 in my code
    let scale: Vector<Real> = Vector2::new(x_scale, 1.0).into();
    Collider::from(SharedShape::heightfield(heights, scale))
```

here's the [xpbd implementation](https://github.com/Jondolf/bevy_xpbd/blob/4d1747304c593733e971757976532a85329d681d/src/plugins/collision/collider/parry/mod.rs#L720-L723)

```
    pub fn heightfield(heights: Vec<Scalar>, scale: Scalar) -> Self {
        SharedShape::heightfield(heights.into(), Vector::splat(scale).into()).into()
    }
```

which looks like it would have the same effect as me using in either `Vector2::new(1.0, 1.0)` or `Vector2::new(511.0, 511.0)` in my code above instead of what I do use, `Vector2::new(511.0, 1.0)` 🤔 

if this is intended behavior, I'll keep working to figure it out 😄 if it isn't, I'd be glad to know 😅

**Comment by Jondolf** [comment]
Yep, this was unintended! Not sure what I was thinking there... #343 fixes it to take a `Vec2`.
