### ISSUE TITLE
dont work gravity

### ISSUE THREAD

**Issue by 5-23** [Jondolf/bevy_xpbd#376]
https://github.com/Jondolf/bevy_xpbd/assets/86705803/8a6a499b-1c1a-447b-a721-9b369a056aa2

**Comment by dror-g** [comment]
Try adding a Collider. 

Not sure about 2D stuff but see the warning: 
`Dynamic rigid body 1v1 has no mass or inertia... consider adding MassPropertiesBundle or a Collider with mass.`

Collider is easiest. it has mass and density by default.

**Comment by 5-23** [comment]
> Try adding a Collider.
> 
> Not sure about 2D stuff but see the warning: `Dynamic rigid body 1v1 has no mass or inertia... consider adding MassPropertiesBundle or a Collider with mass.`
> 
> Collider is easiest. it has mass and density by default.

```rs
fn setup(mut commands: Commands, asset_server: Res<AssetServer>) {
    commands.spawn((
        Collider::rectangle(HITBOX.0, HITBOX.1),
        SpriteBundle {
            sprite: Sprite {
                custom_size: Some(Vec2::new(HITBOX.0, HITBOX.1)),
                ..Default::default()
            },
            texture: asset_server.load("textures/player.png"),
            ..Default::default()
        },
    ));
}
```
don't work..

**Comment by dror-g** [comment]
Sorry mate, but you still need the Rigid Body (dynamic) AND the Collider I think.

**Comment by 5-23** [comment]
its work thx :D
