### ISSUE TITLE
how use add resistance?

### ISSUE THREAD

**Issue by 5-23** [Jondolf/bevy_xpbd#379]

**Comment by Jondolf** [comment]
Hi, what kind of resistance are you looking for? There is the [`Friction`](https://docs.rs/bevy_xpbd_3d/0.4.2/bevy_xpbd_3d/components/struct.Friction.html) component for reducing sliding between objects that are in contact, and there are the [`LinearDamping`](https://docs.rs/bevy_xpbd_3d/0.4.2/bevy_xpbd_3d/components/struct.LinearDamping.html) and [`AngularDamping`](https://docs.rs/bevy_xpbd_3d/0.4.2/bevy_xpbd_3d/components/struct.AngularDamping.html) components for overall reducing the linear and angular velocity over time.

**Comment by 5-23** [comment]
thx!
