### ISSUE TITLE
Child colliders are not handled properly

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [Jondolf/bevy_xpbd#54]
I have a game with a ship as rigid body with a collider and engines attached to it as children, each has colliders and mass as well. I've enabled debug renderer to see the colliders. Engines' colliders don't move with teh ship, but instead stay at (0, 0, 0). Also, they don't have any rotation or scale applied. I'm not sure if this is a bug with only debug renderer, or handling of hierarchy is not even intended, but this does bother me while I'm transitioning to this engine from rapier as an experiment.

**Comment by Jondolf** [comment]
Multiple colliders or colliders as children are unfortunately not implemented yet. I can try to maybe add them in 0.2.

For now, a workaround is to make each engine a separate (dynamic) rigid body, and to connect them to the ship using fixed joints. This way the engines will move and rotate with the ship. This won't help with scale however.

**Comment by ShaddowSpy** [comment]
An fix for this that I'm thinking of is to have a separate change detection function for `Collider`s that are also `Children`. Currently, change detection only triggers when the `Transform` of the entity changes. My proposed solution is to have this second function also trigger when the parent changes `Position`.
Is this a sensible suggestion? I'm thinking there might be edge cases with choosing what to watch among: `Transform`, `GlobalTransform`, and `Position` of the Parent.

**Comment by ShaddowSpy** [comment]
I have come up with a very cursed "solution" to this:
```rust
fn recenter_child(
    mut child_query: Query<&mut Transform, (With<Parent>, With<Collider>)>,
    mut alternate: Local<i8>,
) {
    if *alternate == 0 {
        *alternate = 1
    };
    *alternate *= -1;
    if let Ok(mut child_transform) = child_query.get_single_mut() {
        child_transform.translation = Vec3::new(
            0.001 * *alternate as f32,
            0.0,
            child_transform.translation.z,
        );
    }
}
```

This is my attempt to force change detection on the child entity. This is also undoubtedly the worst rust code I have ever written.
I really hope this is not the optimal way to accomplish this, and I'm not even totally sure as to why this works. I would love some help navigating this issue further.
