### ISSUE TITLE
Cubes start moving after a complete stop

### ISSUE THREAD

**Issue by LeshaInc** [Jondolf/bevy_xpbd#85]
Cubes start moving after a complete stop, as if they are possessed:

https://github.com/Jondolf/bevy_xpbd/assets/42153076/a26206d8-553e-421f-8d9e-cb8c89c3858d

The issue is mitigated by enabling `f64` precision.

Note that it happens even when objects are close to (0, 0) and is unrelated to #84: I've tested both with and without the PR, same result.

**Comment by Jondolf** [comment]
Related to #2 (the end), but this one is more up to date and focused on the drifting

**Comment by Jondolf** [comment]
This is fixed by #90 in terms of collisions against convex meshes like the ground in that video, but I had some problems with non-convex collisions, so there's a separate issue for that: #93
